create extension if not exists pgcrypto;

do $$
begin
  if not exists (select 1 from pg_type where typname = 'request_status') then
    create type public.request_status as enum (
      'draft',
      'awaiting_patient',
      'opened',
      'completed',
      'cancelled',
      'expired'
    );
  end if;
end
$$;

create table if not exists public.sign_requests (
  id uuid primary key default gen_random_uuid(),
  professional_user_id uuid not null references auth.users(id) on delete cascade,
  patient_name text not null,
  patient_phone text not null,
  patient_email text,
  document_title text not null,
  document_snapshot text not null,
  status public.request_status not null default 'draft',
  sign_token text not null unique,
  access_code text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  professional_signed_at timestamptz,
  patient_opened_at timestamptz,
  access_code_validated_at timestamptz,
  consent_accepted_at timestamptz,
  patient_signed_at timestamptz,
  completed_at timestamptz,
  professional_signature text,
  patient_signature text,
  document_hash text not null
);

create table if not exists public.request_events (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.sign_requests(id) on delete cascade,
  event_type text not null check (
    event_type in (
      'request_created',
      'professional_signed',
      'link_opened',
      'access_code_validated',
      'consent_accepted',
      'patient_signed',
      'request_completed'
    )
  ),
  created_at timestamptz not null default now(),
  user_agent text,
  timezone text,
  locale text,
  route_or_origin text,
  actor_type text not null check (actor_type in ('professional', 'patient'))
);

create index if not exists sign_requests_professional_user_id_idx on public.sign_requests(professional_user_id);
create index if not exists sign_requests_sign_token_idx on public.sign_requests(sign_token);
create index if not exists sign_requests_status_idx on public.sign_requests(status);
create index if not exists request_events_request_id_idx on public.request_events(request_id);

create or replace function public.tg_set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sign_requests_set_updated_at on public.sign_requests;
create trigger sign_requests_set_updated_at
before update on public.sign_requests
for each row
execute function public.tg_set_updated_at();

alter table public.sign_requests enable row level security;
alter table public.request_events enable row level security;

drop policy if exists sign_requests_select_own on public.sign_requests;
create policy sign_requests_select_own
on public.sign_requests
for select
to authenticated
using (auth.uid() = professional_user_id);

drop policy if exists sign_requests_insert_own on public.sign_requests;
create policy sign_requests_insert_own
on public.sign_requests
for insert
to authenticated
with check (auth.uid() = professional_user_id);

drop policy if exists sign_requests_update_own on public.sign_requests;
create policy sign_requests_update_own
on public.sign_requests
for update
to authenticated
using (auth.uid() = professional_user_id)
with check (auth.uid() = professional_user_id);

drop policy if exists request_events_select_own on public.request_events;
create policy request_events_select_own
on public.request_events
for select
to authenticated
using (
  exists (
    select 1
    from public.sign_requests sr
    where sr.id = request_events.request_id
      and sr.professional_user_id = auth.uid()
  )
);

drop policy if exists request_events_insert_professional on public.request_events;
create policy request_events_insert_professional
on public.request_events
for insert
to authenticated
with check (
  actor_type = 'professional'
  and exists (
    select 1
    from public.sign_requests sr
    where sr.id = request_events.request_id
      and sr.professional_user_id = auth.uid()
  )
);

create or replace function public.public_open_request(
  p_token text,
  p_user_agent text default null,
  p_timezone text default null,
  p_locale text default null,
  p_route_or_origin text default null
)
returns table (
  id uuid,
  document_title text,
  request_status public.request_status,
  professional_signed_at timestamptz,
  patient_opened_at timestamptz,
  completed_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.sign_requests%rowtype;
begin
  select *
    into v_request
  from public.sign_requests sr
  where sr.sign_token = p_token
    and sr.status in ('awaiting_patient', 'opened', 'completed')
  limit 1;

  if not found then
    return;
  end if;

  if v_request.patient_opened_at is null then
    update public.sign_requests as sr
    set patient_opened_at = now(),
        status = case when sr.status = 'awaiting_patient' then 'opened' else sr.status end,
        updated_at = now()
    where sr.id = v_request.id
    returning * into v_request;

    insert into public.request_events (
      request_id,
      event_type,
      actor_type,
      user_agent,
      timezone,
      locale,
      route_or_origin
    )
    values (
      v_request.id,
      'link_opened',
      'patient',
      p_user_agent,
      p_timezone,
      p_locale,
      p_route_or_origin
    );
  end if;

  return query
  select
    v_request.id,
    v_request.document_title,
    v_request.status as request_status,
    v_request.professional_signed_at,
    v_request.patient_opened_at,
    v_request.completed_at;
end;
$$;

create or replace function public.public_validate_access_code(
  p_token text,
  p_access_code text,
  p_user_agent text default null,
  p_timezone text default null,
  p_locale text default null,
  p_route_or_origin text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.sign_requests%rowtype;
begin
  select *
    into v_request
  from public.sign_requests sr
  where sr.sign_token = p_token
    and sr.status in ('awaiting_patient', 'opened', 'completed')
  limit 1;

  if not found then
    return false;
  end if;

  if p_access_code is null or trim(v_request.access_code) <> trim(p_access_code) then
    return false;
  end if;

  if v_request.access_code_validated_at is null then
    update public.sign_requests
    set access_code_validated_at = now(),
        updated_at = now()
    where public.sign_requests.id = v_request.id;

    insert into public.request_events (
      request_id,
      event_type,
      actor_type,
      user_agent,
      timezone,
      locale,
      route_or_origin
    )
    values (
      v_request.id,
      'access_code_validated',
      'patient',
      p_user_agent,
      p_timezone,
      p_locale,
      p_route_or_origin
    );
  end if;

  return true;
end;
$$;

create or replace function public.public_get_review_request(
  p_token text
)
returns table (
  id uuid,
  patient_name text,
  document_title text,
  document_snapshot text,
  document_hash text,
  professional_signature text,
  request_status public.request_status,
  consent_accepted_at timestamptz,
  patient_signed_at timestamptz,
  completed_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select
    sr.id,
    sr.patient_name,
    sr.document_title,
    sr.document_snapshot,
    sr.document_hash,
    sr.professional_signature,
    sr.status as request_status,
    sr.consent_accepted_at,
    sr.patient_signed_at,
    sr.completed_at
  from public.sign_requests sr
  where sr.sign_token = p_token
    and sr.access_code_validated_at is not null;
$$;

create or replace function public.public_accept_consent(
  p_token text,
  p_user_agent text default null,
  p_timezone text default null,
  p_locale text default null,
  p_route_or_origin text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.sign_requests%rowtype;
begin
  select *
    into v_request
  from public.sign_requests sr
  where sr.sign_token = p_token
    and access_code_validated_at is not null
    and sr.status in ('awaiting_patient', 'opened', 'completed')
  limit 1;

  if not found then
    return false;
  end if;

  if v_request.consent_accepted_at is null then
    update public.sign_requests
    set consent_accepted_at = now(),
        updated_at = now()
    where public.sign_requests.id = v_request.id;

    insert into public.request_events (
      request_id,
      event_type,
      actor_type,
      user_agent,
      timezone,
      locale,
      route_or_origin
    )
    values (
      v_request.id,
      'consent_accepted',
      'patient',
      p_user_agent,
      p_timezone,
      p_locale,
      p_route_or_origin
    );
  end if;

  return true;
end;
$$;

create or replace function public.public_patient_sign_request(
  p_token text,
  p_patient_signature text,
  p_user_agent text default null,
  p_timezone text default null,
  p_locale text default null,
  p_route_or_origin text default null
)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_request public.sign_requests%rowtype;
begin
  select *
    into v_request
  from public.sign_requests sr
  where sr.sign_token = p_token
    and access_code_validated_at is not null
    and consent_accepted_at is not null
    and sr.status in ('awaiting_patient', 'opened', 'completed')
  limit 1;

  if not found then
    return false;
  end if;

  if v_request.patient_signed_at is null then
    update public.sign_requests
    set patient_signature = p_patient_signature,
        patient_signed_at = now(),
        completed_at = now(),
        status = 'completed',
        updated_at = now()
    where public.sign_requests.id = v_request.id;

    insert into public.request_events (
      request_id,
      event_type,
      actor_type,
      user_agent,
      timezone,
      locale,
      route_or_origin
    )
    values (
      v_request.id,
      'patient_signed',
      'patient',
      p_user_agent,
      p_timezone,
      p_locale,
      p_route_or_origin
    );

    insert into public.request_events (
      request_id,
      event_type,
      actor_type,
      user_agent,
      timezone,
      locale,
      route_or_origin
    )
    values (
      v_request.id,
      'request_completed',
      'patient',
      p_user_agent,
      p_timezone,
      p_locale,
      p_route_or_origin
    );
  end if;

  return true;
end;
$$;

grant execute on function public.public_open_request(text, text, text, text, text) to anon, authenticated;
grant execute on function public.public_validate_access_code(text, text, text, text, text, text) to anon, authenticated;
grant execute on function public.public_get_review_request(text) to anon, authenticated;
grant execute on function public.public_accept_consent(text, text, text, text, text) to anon, authenticated;
grant execute on function public.public_patient_sign_request(text, text, text, text, text, text) to anon, authenticated;
